- name: GPSD Setup
  block:
    - name: Setting up GPSD Service
      lineinfile:
        path: /etc/default/gpsd
        regexp: '^GPSD_OPTIONS=""'
        line: GPSD_OPTIONS="-n -G"
        owner: root
        group: root
        mode: '0644'

    - name: Setting up GPSD Listen ports
      lineinfile:
        path: /lib/systemd/system/gpsd.socket
        regexp: '^ListenStream=127.0.0.1:2947'
        line: ListenStream=0.0.0.0:2947    
        owner: root
        group: root
        mode: '0644'

    - name: Setting up GPSD Listen ports
      lineinfile:
        path: /lib/systemd/system/gpsd.socket
        insertbefore: 'ListenStream=/var/run/gpsd.sock'
        line: ListenStream=
        state: present

    - name: Setting up GPSD Service file
      lineinfile:
        dest: /lib/systemd/system/gpsd.service
        insertbefore: "{{ item.insertbefore }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - { insertbefore: 'EnvironmentFile=-/etc/sysconfig/gpsd', line: 'EnvironmentFile=-/etc/default/gpsd' }
        - { insertbefore: 'Also=gpsd.socket', line: 'WantedBy=multi-user.target' }

    - name: Setting up GPSD Service file
      lineinfile:
        path: /lib/systemd/system/gpsd.service
        regexp: '^ExecStart=/usr/sbin/gpsd $GPSD_OPTIONS $DEVICES'
        line: ExecStart=/usr/sbin/gpsd -N $GPSD_OPTIONS $DEVICES    
        owner: root
        group: root
        mode: '0644'

    - name: Sync system time with GPS Receiver
      lineinfile:
        path: /etc/chrony/chrony.conf
        state: present
        line: "{{ item }}"
      loop:
        - refclock SHM  0 delay 0.5 refid GPS