#- name: Generate Sky Hub certificates
#  shell: |
#    sudo docker run -d \
#        --name skyhub-gpsd --privileged --restart always --ipc=host \
#        --network skyhub-network ---log-opt max-size=10m \
#        skyhuborg/gpsd:latest -D2 /dev/$(readlink /dev/skyhub-gps)
#    exit 0
#  args:
#    executable: /bin/bash

- name: Setup GPSD container
  community.general.docker_container:
    name: skyhub-gpsd
    image: skyhuborg/gpsd:latest
    state: started
    restart: no
    restart_policy: always
    privileged: yes
    ipc_mode: host
    command: -D2 /dev/$(readlink /dev/skyhub-gps)


# - name: Disable GPSD
#   systemd:
#     name: "{{ item }}"
#     state: stopped
#     enabled: no
#   become: true
#   loop: 
#     - skyhub-gpsd.service
#     - skyhub-gpsd.socket
#   ignore_errors: true
  
# - name: Sync system time with GPS Receiver
#   lineinfile:
#     path: /etc/chrony/chrony.conf
#     state: present
#     line: "{{ item }}"
#   loop:
#     - refclock SHM  0 delay 0.5 refid GPS

# - name: Enable GPSD
#   systemd:
#     name: "{{ item }}"
#     state: restarted
#     enabled: yes
#     daemon_reload: yes
#   become: true
#   loop:
#     - skyhub-gpsd.service
#     - skyhub-gpsd.socket
