- hostname:
    name: skyhub-tracker

- name: Upgrade packages
  apt:
    upgrade: dist
    update_cache: yes

- name: Install packages
  apt:
    name: "{{ item }}"
  loop:
    - docker.io
    - python-pip
    - avahi-daemon
    - git
    - docker-compose
    - nvidia-container-csv-cuda
    - nvidia-container-csv-cudnn 
    - nvidia-container-csv-tensorrt
    - nvidia-container-csv-visionworks
    - deepstream-5.0

- pip:
    name: jetson-stats

- name: Creating Sky Hub User
  user:
    name: skyhub
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    shell: /bin/bash
    password: skyhub123
    groups: docker


- name: Adding Sky Hub user to sudoers
  lineinfile:
    path: /etc/sudoers
    state: present
    line: "skyhub ALL=(ALL) NOPASSWD:/skyhub/skyhub"

- name: Create directories for Tracker
  file:
    path: "{{ item }}"
    state: directory
    owner: skyhub
    group: skyhub
    mode: 0755
  loop:
    - /skyhub
    - /skyhub/storage
    - /skyhub/storage/mysql
    - /skyhub/storage/certs

- name: Cloning get-started repository
  git:
    repo: https://gitlab.com/skyhuborg/get-started.git
    dest: ~/get-started
    update: yes

- name: Copying Sky Hub CLI
  copy:
    src: ~/get-started/deploy/
    dest: /skyhub

- name: Configuring udev rules
  copy:
    src: "{{ item }}"
    dest: /etc/udev/rules.d/
  loop:
    - ./files/99-skyhub-device.rules

- name: Reloading udev rules
  shell:
    cmd: udevadm control --reload-rules && udevadm trigger

- name: Installing service definitions
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system/
    mode: 644
  loop:
    - ./files/skyhub-pipe.service
    - ./files/skyhub-clocks.service

- name: Installing clock service
  copy:
    src: "{{ item }}"
    dest: /skyhub/
    mode: u+rwx
  loop:
    - ./files/clock.sh
    - ./files/skyhub-pipe

- name: Installing Sky Hub pipe
  copy:
    src: "{{ item }}"
    dest: /skyhub/
    mode: 666
  loop:
    - ./files/skyhub-pipe

- name: Reloading systemctl daemon
  systemd:
    daemon_reload: yes

- name: Enable services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  become: true
  loop:
    - avahi-daemon
    - ssh
    - docker
    - skyhub-pipe
    - skyhub-clocks


#- name: Generate Sky Hub certificates
#  shell: |
#    openssl genrsa -out /skyhub/storage/certs/ca.key 4096
#    openssl req -new -x509 -key /skyhub/storage/certs/ca.key -sha256 -batch -config ./files/openssl.cnf -days 1825 -out /skyhub/storage/certs/ca.cert
#    openssl genrsa -out /skyhub/storage/certs/service.key 4096
#    openssl req -new -key /skyhub/storage/certs/service.key -batch -config ./files/openssl.cnf -out /skyhub/storage/certs/service.csr 
#    openssl x509 -req -in /skyhub/storage/certs/service.csr -CA /skyhub/storage/certs/ca.cert -CAkey /skyhub/storage/certs/ca.key -CAcreateserial -out /skyhub/storage/certs/service.pem -days 1825 -sha256 -extfile ./files/openssl.cnf -extensions v3_ca
#    exit 0a
#  args:
#    executable: /bin/bash


- name: Blacklist kernel modules
  kernel_blacklist:
    name: "{{ item }}"
    state: present
  loop:
    - bluedroid_pm

