#!/bin/bash

echo "Setting up Sky Hub Installer..."

apt-get -qq update 
apt-get install -qq -y git ansible

if [ ! -d ansible-tracker ]; then
	git -q clone https://gitlab.com/skyhuborg/ansible-tracker.git
else
	pushd ansible-tracker
	git pull
	popd
fi

cd ansible-tracker
