#!/bin/bash

echo "Initializing the Sky Hub Installer..."
GITBRANCH=master
TRACKERENV=prod
case $1 in

  dev)
    echo "Running dev environment"
    GITBRANCH=develop
    TRACKERENV=dev
    ;;

  test)
    echo "Running test environment"
    GITBRANCH=test
    TRACKERENV=test
    ;;

  staging)
    echo "Running staging / prod environment"
    GITBRANCH=develop
    TRACKERENV=prod
    ;;

  *)
    echo "Running prod environment"
    ;;
esac

echo "Installing ansible, this step may take a while."
apt-get -qq update 
apt-get install -qq -y git python3-pip python-pip

pip3 -q install ansible

ansible-galaxy collection install ansible.posix -p ~/.ansible/collections
ansible-galaxy collection install community.general -p ~/.ansible/collections

if [ -d ansible-tracker ]; then
	rm -rf ./ansible-tracker
fi

git clone -q https://gitlab.com/skyhuborg/ansible-tracker.git

cd ansible-tracker
git checkout $GITBRANCH

if [ $TRACKERENV = "dev" ]; then
  ansible-playbook $TRACKERENV.yml
else
  ANSIBLE_STDOUT_CALLBACK=actionable ansible-playbook $TRACKERENV.yml
fi

cd ..
rm -r ./ansible-tracker
rm ./install

#this is for when we go to production
