- name: Apply baseline configuration for tracker.
  hosts: all
  connection: local
  roles:
    - baseline
  vars:
    existing_install: 'false'
    needs_cleanup: 'false'
    storage_configured: 'false'
    tracker_env: 'prod' 
    git_branch: 'master'
    upload_server_addr: 'https://trackerd-upload.skyhub.org'
    trackerd_server_addr: 'trackerd.skyhub.org:8088'
    trackerd_auto_tls_name: 'trackerd.skyhub.org'
