- name: Apply baseline configuration for tracker.
  hosts: all
  connection: local
  roles:
    - baseline
  vars:
    existing_install: 'false'
    needs_cleanup: 'false'
    storage_configure: 'false'
    env: 'test' 